config/routes.rb
Amz::Application.routes.draw do

resources :lookups

root :to => "lookups#index"

end

app/models/lookup.rb
class Lookup < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/lookups_controller.rb
class LookupsController < ApplicationController
  # GET /lookups
  # GET /lookups.xml
  def index
    require 'rexml/document' 
    require 'hmac-sha2'
    require 'open-uri'

    @SecretKey='l1OK46EWvCPid1jKYBzWR0aT1jz1U+luT5CG/VHm'
    @AWSAccessKeyId='AKIAIWVW3RXPPPYYY6DA'
    @ItemId="0679722769"
    @Operation="ItemSearch"
    @ResponseGroup="Large"
    @Keywords=if params[:keywords]==nil then "Camera" else params[:keywords] end
    @SearchIndex='Photo'
    if !(@Brand=params[:brand]) then @Brand=" " end
    @BrowseNode='330405011';   #Point & Shoot Digital Cameras
    @Service='AWSECommerceService'
    @Timestamp=CGI.escape(Time.new.strftime("%Y-%m-%dT%H:%M:%SPDT"))
    @Version='2009-01-06'

    @sstring=''
#    @sstring="GET\nwebservices.amazon.com\n/onca/xml\n"
    @sstring+='AWSAccessKeyId='+@AWSAccessKeyId
    @sstring+='&Brand='+@Brand
    @sstring+='&BrowseNode='+@BrowseNode
    @sstring+='&Keywords='+URI.escape(@Keywords)
    @sstring+='&Operation='+@Operation
    @sstring+='&ResponseGroup='+@ResponseGroup
    @sstring+='&SearchIndex='+@SearchIndex
    @sstring+='&Service='+@Service
    @sstring+='&Timestamp='+@Timestamp
    @sstring+='&Version='+@Version

    @aaaqs='http://webservices.amazon.com/onca/xml?'+@sstring   

    hmac = HMAC::SHA256.new(@SecretKey)
    hmac.update("GET\nwebservices.amazon.com\n/onca/xml\n"+@sstring)
    @aaaqs+='&Signature='+CGI::escape(Base64.encode64(hmac.digest).chomp)
## chomp is important! the base64 encoded version will have a newline at the end

    @doc= REXML::Document.new open(@aaaqs).read
    @ItemArray=Array.new

    @NumItems=@doc.elements["ItemSearchResponse/Items/TotalResults"].text
    @NumPages=@doc.elements["ItemSearchResponse/Items/TotalPages"].text

    @doc.elements.to_a("ItemSearchResponse/Items/Item/").each do |items|
      @ItemArray << [items.elements["*/Title"], items.elements["*/Manufacturer"], items.elements["*/LowestNewPrice/FormattedPrice"]]
   end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lookups_helper.rb
module LookupsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Amz</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/lookups/_form.html.erb
<%= form_for(@lookup) do |f| %>
  <% if @lookup.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@lookup.errors.count, "error") %> prohibited this lookup from being saved:</h2>

      <ul>
      <% @lookup.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :q %><br />
    <%= f.text_field :q %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/lookups/edit.html.erb
<h1>Editing lookup</h1>

<%= render 'form' %>

<%= link_to 'Show', @lookup %> |
<%= link_to 'Back', lookups_path %>

app/views/lookups/index.html.erb
<h1>Amazon Search Results</h1>

<%= form_tag lookups_path, :method => "get"  do %>
<table>
<tr>
<td><%= label_tag(:kwlabel, "Keywords") %></td>
<td><%= text_field_tag(:keywords, @Keywords) %></td>
</tr>  
<tr>  
<td><%= label_tag(:brandlabel, "Brand") %></td>
<td><%= text_field_tag(:brand, @Brand) %></td>
</tr>  
<tr>
<td><%= submit_tag("Search") %></td>
</tr>
<% end %>
</table>

<% if false %>
<p> @Keywords: <%=@Keywords %> </p>
<p> @ResponseGroup: <%=@ResponseGroup %> </p>
<p> @sstring: <%=@sstring %> </p>

<p> @ItemArray: <%=@ItemArray.to_s %> </p>
<p> @ItemArray[0]: <%=@ItemArray[0].to_s %> </p>
<p> @ItemArray[0][0]: <%=@ItemArray[0][0] %> </p>
<% end %>

<p> @aaaqs: <%=@aaaqs %> </p>

<p>Results/Pages: <%=@NumItems%>/<%=@NumPages%>  </p>

<table>
  <tr>
    <th width="50%" align="center">Title </th>
    <th align="left">Manufacturer</th>
    <th align="left">Price</th>
    <th></th>
  </tr>

<% if false %>
<% end %>

<% @ItemArray.each do |i| %>
<tr>
  <% k=0 %>
  <% i.each do |j| %>
  <% if k then %>
  <td width ="10%" align="left"> <%= if j then j.text end %> </td>
  <% else %>
  <td width="50%" align="left"> <%= if j then j.text end %> </td>
	     <% end %>
  
  <% end %>
</tr>
<% end %>
</table>

app/views/lookups/new.html.erb
<h1>New lookup</h1>

<%= render 'form' %>

<%= link_to 'Back', lookups_path %>

app/views/lookups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Q:</b>
  <%= @lookup.q %>
</p>


<%= link_to 'Edit', edit_lookup_path(@lookup) %> |
<%= link_to 'Back', lookups_path %>